python3 run_train.py \
--diff_steps 2000 \
--lr 0.0001 \
--learning_steps 300000 \
--save_interval  1000 \
--seed 102 \
--noise_schedule sqrt \
--hidden_dim 128 \
--bsz 128 \
--microbatch 128 \
--dataset dialogue \
--data_dir  /home/aiuser/Jittor-DiffuSeq/datasets/CommonsenseConversation \
--vocab bert \
--seq_len 128 \
--schedule_sampler lossaware \
--notes dialogue
